# Military Data Cleaning

This notebook processes the raw scraped dataset.
The workflow includes data cleaning, column filtering, renaming the columns and sorting them alphabetically.

### Import Required Libraries

In [1]:
import pandas as pd
import re

### Load Raw Scraped Dataset

The raw dataset generated from the scraping pipeline
is loaded into a DataFrame for cleaning and processing.

In [2]:
df = pd.read_csv("military_raw_data.csv")

df.head()

,country,power_index_rank,power_index_score,purchasing_power_parity,foreign_exchange/gold,defense_budget,external_debt,square_land_area,coastline_coverage,shared_borders,...,coal_deficit,coal_proven_reserves,internet_coverage,labor_force,merchant_marine_fleet,ports_/_trade_terminals,airports,roadway_coverage,railway_coverage,total_tonnage
0,2026Democratic Republic of the Congo Military ...,64,1.3051,80,105,98,41,11,3,125,...,"-304,000 mt",44,48,17,102,44,24,34,47,NaN
1,2026Honduras Military Strength,103,2.2575,106,86,112,40,97,39,35,...,"-144,000 mt",145,35,91,36,39,37,120,97,NaN
2,2026Finland Military Strength,48,0.8673,60,68,40,127,63,46,62,...,"-3,122,000 mt",145,7,105,46,19,48,48,33,50.0
3,2026Bulgaria Military Strength,62,1.2522,73,51,73,57,99,18,43,...,"+413,000 mt",31,21,101,75,45,43,112,45,NaN
4,2026Nepal Military Strength,124,2.8037,82,76,121,30,90,999,72,...,"-1,082,000 mt",74,37,63,145,145,70,77,120,NaN

In [3]:
#standardize everything
df.columns = (
    df.columns
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("-", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace(".", "", regex=False)
    .str.replace("*", "", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)
df.head()

,country,power_index_rank,power_index_score,purchasing_power_parity,foreign_exchange_gold,defense_budget,external_debt,square_land_area,coastline_coverage,shared_borders,...,coal_deficit,coal_proven_reserves,internet_coverage,labor_force,merchant_marine_fleet,ports___trade_terminals,airports,roadway_coverage,railway_coverage,total_tonnage
0,2026Democratic Republic of the Congo Military ...,64,1.3051,80,105,98,41,11,3,125,...,"-304,000 mt",44,48,17,102,44,24,34,47,NaN
1,2026Honduras Military Strength,103,2.2575,106,86,112,40,97,39,35,...,"-144,000 mt",145,35,91,36,39,37,120,97,NaN
2,2026Finland Military Strength,48,0.8673,60,68,40,127,63,46,62,...,"-3,122,000 mt",145,7,105,46,19,48,48,33,50.0
3,2026Bulgaria Military Strength,62,1.2522,73,51,73,57,99,18,43,...,"+413,000 mt",31,21,101,75,45,43,112,45,NaN
4,2026Nepal Military Strength,124,2.8037,82,76,121,30,90,999,72,...,"-1,082,000 mt",74,37,63,145,145,70,77,120,NaN

### Initial Data Cleaning

We:
- Remove commas from numeric values
- Convert relevant columns to numeric format
- Handle missing values

In [4]:
#standardize everything
def clean_numeric(value):
    if pd.isna(value):
        return None
    value = re.sub(r"[^\d.]", "", str(value))
    return float(value) if value else None

for col in df.columns:
    if col != "country":
        df[col] = df[col].apply(clean_numeric)

df.head()

,country,power_index_rank,power_index_score,purchasing_power_parity,foreign_exchange_gold,defense_budget,external_debt,square_land_area,coastline_coverage,shared_borders,...,coal_deficit,coal_proven_reserves,internet_coverage,labor_force,merchant_marine_fleet,ports___trade_terminals,airports,roadway_coverage,railway_coverage,total_tonnage
0,2026Democratic Republic of the Congo Military ...,64.0,1.3051,80.0,105.0,98.0,41.0,11.0,3.0,125.0,...,304000.0,44.0,48.0,17.0,102.0,44.0,24.0,34.0,47.0,NaN
1,2026Honduras Military Strength,103.0,2.2575,106.0,86.0,112.0,40.0,97.0,39.0,35.0,...,144000.0,145.0,35.0,91.0,36.0,39.0,37.0,120.0,97.0,NaN
2,2026Finland Military Strength,48.0,0.8673,60.0,68.0,40.0,127.0,63.0,46.0,62.0,...,3122000.0,145.0,7.0,105.0,46.0,19.0,48.0,48.0,33.0,50.0
3,2026Bulgaria Military Strength,62.0,1.2522,73.0,51.0,73.0,57.0,99.0,18.0,43.0,...,413000.0,31.0,21.0,101.0,75.0,45.0,43.0,112.0,45.0,NaN
4,2026Nepal Military Strength,124.0,2.8037,82.0,76.0,121.0,30.0,90.0,999.0,72.0,...,1082000.0,74.0,37.0,63.0,145.0,145.0,70.0,77.0,120.0,NaN

### Remove the "2026" & "Military Strength" from "Country"

In [5]:
df = (
    df.assign(
        country=df["country"]
        .str.replace(r"\s*\d{4}", "", regex=True)
        .str.strip()
    ))
df = (
    df.assign(
        country=df["country"]
        .str.replace(r"Military Strength", "", case=False)
        .str.replace(r"\s*\d{4}", "", regex=True)
        .str.strip()
    )    
    .sort_values("country")
    .reset_index(drop=True))

df.head()

,country,power_index_rank,power_index_score,purchasing_power_parity,foreign_exchange_gold,defense_budget,external_debt,square_land_area,coastline_coverage,shared_borders,...,coal_deficit,coal_proven_reserves,internet_coverage,labor_force,merchant_marine_fleet,ports___trade_terminals,airports,roadway_coverage,railway_coverage,total_tonnage
0,Afghanistan,121.0,2.7342,101.0,84.0,136.0,8.0,41.0,999.0,109.0,...,264000.0,71.0,57.0,59.0,145.0,145.0,61.0,94.0,145.0,NaN
1,Albania,77.0,1.7258,121.0,91.0,107.0,28.0,132.0,19.0,16.0,...,218000.0,50.0,18.0,127.0,81.0,44.0,107.0,139.0,114.0,NaN
2,Algeria,27.0,0.4849,40.0,34.0,23.0,26.0,10.0,43.0,115.0,...,3000.0,61.0,23.0,46.0,63.0,30.0,49.0,47.0,46.0,33.0
3,Angola,59.0,1.1045,63.0,72.0,20.0,85.0,22.0,54.0,102.0,...,0.0,145.0,39.0,41.0,83.0,27.0,43.0,68.0,61.0,NaN
4,Argentina,32.0,0.5983,29.0,59.0,97.0,96.0,8.0,88.0,126.0,...,1665000.0,47.0,12.0,33.0,50.0,19.0,10.0,18.0,16.0,25.0

In [6]:
# Finalized column list
final_columns = [
    "country",
    "power_index_score",
    "power_index_rank",

    "active_personnel",
    "reserve_personnel",
    "available_manpower",
    "total_population",

    "aircraft_total",
    "fighters",
    "attack_helicopters",

    "tanks",
    "self_propelled_artillery",
    "mlrs_rocket_artillery",

    "total_assets",
    "submarines",
    "destroyers",
    "frigates",
    "aircraft_carriers",

    "defense_budget",
    "purchasing_power_parity",
    "foreign_exchange_gold",

    "oil_production",
    "oil_consumption",
    "oil_proven_reserves",
    "natural_gas_production",
    "natural_gas_consumption"
]

# Keep only finalized columns
df = df[final_columns]

# Reset index for clean structure
df = df.reset_index(drop=True)

# Quick verification
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   country                   145 non-null    str
 1   power_index_score         145 non-null    float64
 2   power_index_rank          145 non-null    float64
 3   active_personnel          145 non-null    float64
 4   reserve_personnel         145 non-null    float64
 5   available_manpower        145 non-null    float64
 6   total_population          145 non-null    float64
 7   aircraft_total            145 non-null    float64
 8   fighters                  145 non-null    float64
 9   attack_helicopters        145 non-null    float64
 10  tanks                     145 non-null    float64
 11  self_propelled_artillery  145 non-null    float64
 12  mlrs_rocket_artillery     145 non-null    float64
 13  total_assets              113 non-null    float64
 14  submarines                113 non-null    float64
 15  destroyers                113 non-null    float64
 16  frigates                  113 non-null    float64
 17  aircraft_carriers         113 non-null    float64
 18  defense_budget            145 non-null    float64
 19  purchasing_power_parity   145 non-null    float64
 20  foreign_exchange_gold     145 non-null    float64
 21  oil_production            145 non-null    float64
 22  oil_consumption           145 non-null    float64
 23  oil_proven_reserves       145 non-null    float64
 24  natural_gas_production    145 non-null    float64
 25  natural_gas_consumption   145 non-null    float64
dtypes: float64(25), str(1)
memory usage: 29.6 KB

,country,power_index_score,power_index_rank,active_personnel,reserve_personnel,available_manpower,total_population,aircraft_total,fighters,attack_helicopters,...,frigates,aircraft_carriers,defense_budget,purchasing_power_parity,foreign_exchange_gold,oil_production,oil_consumption,oil_proven_reserves,natural_gas_production,natural_gas_consumption
0,Afghanistan,2.7342,121.0,65.0,145.0,43.0,36.0,108.0,145.0,145.0,...,NaN,NaN,136.0,101.0,84.0,145.0,38.0,145.0,73.0,10.0
1,Albania,1.7258,77.0,134.0,145.0,128.0,127.0,97.0,145.0,145.0,...,145.0,145.0,107.0,121.0,91.0,64.0,15.0,53.0,80.0,7.0
2,Algeria,0.4849,27.0,42.0,38.0,29.0,33.0,16.0,20.0,10.0,...,11.0,145.0,23.0,40.0,34.0,16.0,94.0,15.0,10.0,94.0
3,Angola,1.1045,59.0,53.0,145.0,67.0,40.0,35.0,29.0,31.0,...,145.0,145.0,20.0,63.0,72.0,18.0,61.0,18.0,44.0,32.0
4,Argentina,0.5983,32.0,52.0,79.0,32.0,34.0,41.0,48.0,145.0,...,145.0,145.0,97.0,29.0,59.0,22.0,103.0,30.0,17.0,92.0

### Handle Missing Values
#Drop columns with>50% missing values

#We replace missing numeric values (`NaN`) with the median of each column.  
The median is chosen because it is robust to extreme values and reduces distortion caused by outliers.  
This ensures the dataset contains no missing values before further analysis or modeling.

In [7]:
missing_percent = df.isna().mean() * 100
cols_to_drop = missing_percent[missing_percent > 50].index
df.drop(columns=cols_to_drop, inplace=True)

In [8]:
df.fillna(df.median(numeric_only=True), inplace=True)

,country,power_index_score,power_index_rank,active_personnel,reserve_personnel,available_manpower,total_population,aircraft_total,fighters,attack_helicopters,...,frigates,aircraft_carriers,defense_budget,purchasing_power_parity,foreign_exchange_gold,oil_production,oil_consumption,oil_proven_reserves,natural_gas_production,natural_gas_consumption
0,Afghanistan,2.7342,121.0,65.0,145.0,43.0,36.0,108.0,145.0,145.0,...,145.0,145.0,136.0,101.0,84.0,145.0,38.0,145.0,73.0,10.0
1,Albania,1.7258,77.0,134.0,145.0,128.0,127.0,97.0,145.0,145.0,...,145.0,145.0,107.0,121.0,91.0,64.0,15.0,53.0,80.0,7.0
2,Algeria,0.4849,27.0,42.0,38.0,29.0,33.0,16.0,20.0,10.0,...,11.0,145.0,23.0,40.0,34.0,16.0,94.0,15.0,10.0,94.0
3,Angola,1.1045,59.0,53.0,145.0,67.0,40.0,35.0,29.0,31.0,...,145.0,145.0,20.0,63.0,72.0,18.0,61.0,18.0,44.0,32.0
4,Argentina,0.5983,32.0,52.0,79.0,32.0,34.0,41.0,48.0,145.0,...,145.0,145.0,97.0,29.0,59.0,22.0,103.0,30.0,17.0,92.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Venezuela,0.9106,51.0,51.0,82.0,44.0,49.0,43.0,42.0,35.0,...,18.0,145.0,51.0,90.0,79.0,23.0,76.0,1.0,34.0,72.0
141,Vietnam,0.4066,23.0,11.0,1.0,12.0,16.0,38.0,31.0,145.0,...,10.0,145.0,35.0,25.0,33.0,35.0,97.0,23.0,42.0,61.0
142,Yemen,2.1617,98.0,90.0,145.0,51.0,48.0,52.0,28.0,31.0,...,145.0,145.0,124.0,136.0,132.0,63.0,38.0,27.0,70.0,14.0
143,Zambia,2.4461,111.0,122.0,145.0,68.0,62.0,73.0,145.0,145.0,...,145.0,145.0,126.0,103.0,116.0,145.0,25.0,145.0,145.0,1.0
144,Zimbabwe,2.2801,105.0,96.0,145.0,72.0,71.0,72.0,59.0,39.0,...,145.0,145.0,77.0,114.0,139.0,79.0,25.0,145.0,145.0,1.0

### Data Ordering and Column Alignment

In [9]:

df = df.sort_values("country")
df = df.reset_index(drop=True)
df = df.reindex(sorted(df.columns), axis=1)
df = df[["country"] + [col for col in df.columns if col != "country"]]


df.head()

,country,active_personnel,aircraft_carriers,aircraft_total,attack_helicopters,available_manpower,defense_budget,destroyers,fighters,foreign_exchange_gold,...,oil_proven_reserves,power_index_rank,power_index_score,purchasing_power_parity,reserve_personnel,self_propelled_artillery,submarines,tanks,total_assets,total_population
0,Afghanistan,65.0,145.0,108.0,145.0,43.0,136.0,145.0,145.0,84.0,...,145.0,121.0,2.7342,101.0,145.0,145.0,145.0,145.0,53.0,36.0
1,Albania,134.0,145.0,97.0,145.0,128.0,107.0,145.0,145.0,91.0,...,53.0,77.0,1.7258,121.0,145.0,67.0,145.0,145.0,57.0,127.0
2,Algeria,42.0,145.0,16.0,10.0,29.0,23.0,145.0,20.0,34.0,...,15.0,27.0,0.4849,40.0,38.0,21.0,12.0,13.0,33.0,33.0
3,Angola,53.0,145.0,35.0,31.0,67.0,20.0,145.0,29.0,72.0,...,18.0,59.0,1.1045,63.0,145.0,57.0,145.0,45.0,58.0,40.0
4,Argentina,52.0,145.0,41.0,145.0,32.0,97.0,9.0,48.0,59.0,...,30.0,32.0,0.5983,29.0,79.0,60.0,15.0,36.0,52.0,34.0

### Export Cleaned Dataset

The final processed dataset is exported
for Tableau dashboard and visualization usage.

In [10]:
df.to_csv("military_cleaned.csv", index=False)

In [11]:
# to list the names of the columns
print(df.columns.tolist())

['country', 'active_personnel', 'aircraft_carriers', 'aircraft_total', 'attack_helicopters', 'available_manpower', 'defense_budget', 'destroyers', 'fighters', 'foreign_exchange_gold', 'frigates', 'mlrs_rocket_artillery', 'natural_gas_consumption', 'natural_gas_production', 'oil_consumption', 'oil_production', 'oil_proven_reserves', 'power_index_rank', 'power_index_score', 'purchasing_power_parity', 'reserve_personnel', 'self_propelled_artillery', 'submarines', 'tanks', 'total_assets', 'total_population']

In [12]:
# finding the specific column by filling the expected words inside "".
for col in df.columns:
    if "air" in col.lower():
        print(col)

aircraft_carriers
aircraft_total