In [ ]:
import pandas as pd

df = pd.read_csv('/content/Military_clean_data.csv')
print("Data loaded successfully into a DataFrame named 'df'.")
df

Data loaded successfully into a DataFrame named 'df'.

,Country_Code,Country_Name,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,...,natural_gas_production_cum,natural_gas_consumption_cum,proven_natural_gas_reserves_cum,coal_production_cum,coal_consumption_mt,proven_coal_reserves_cum,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km
0,USA,United States,341963408,150463900,"124,816,644",4445524,1333030,799500,0,13032,...,1.029000e+12,9.143010e+11,1.340200e+13,5.342340e+08,495156000,2.478830e+11,9833517,19924,12002,41009
1,RUS,Russia,140820810,69002197,"46,189,226",1267387,1320000,2000000,250000,4237,...,6.178300e+11,4.722390e+11,4.780500e+13,5.311300e+08,290763000,1.621660e+11,17098242,37653,22407,102000
2,CHN,China,1415043270,764123366,"626,864,169",19810606,2035000,510000,625000,3529,...,2.253410e+11,3.661600e+11,6.654000e+12,4.805000e+09,5191000000,1.570410e+11,9596960,14500,22457,27700
3,IND,India,1409128296,662290299,"522,786,598",23955181,1431000,1000000,2527000,2183,...,3.317000e+10,5.886700e+10,1.381000e+12,1.020000e+09,1262000000,1.277270e+11,3287263,7000,13888,14500
4,SKO,South Korea,52081799,26040900,"21,353,538",416654,450000,3100000,120000,1540,...,5.512700e+07,5.948000e+10,7.079000e+09,1.608100e+07,136817000,3.260000e+08,99720,2413,237,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,LIB,Liberia,5437249,2392390,"1,913,912",65247,2100,0,5500,0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,0.000000e+00,111369,579,1667,0
141,SRN,Suriname,646758,142287,"84,079",3234,2500,0,200,3,...,7.109000e+06,6.967000e+06,0.000000e+00,0.000000e+00,0,0.000000e+00,163820,386,1907,1200
142,CAR,Central African Republic,5650957,2203873,"1,254,512",101717,30000,0,1000,8,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,3.000000e+06,622984,0,5920,2800
143,BLZ,Beliz,415789,158000,"90,226",8732,2000,850,0,3,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,0.000000e+00,22966,386,542,825
144,BUT,Bhutan,884546,203446,"122,067",4423,16000,50000,0,2,...,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+03,105000,0.000000e+00,38394,0,1136,0

In [ ]:
# normalized assets by manpower (per capita approach)

# calculated defense spending intensity using GDP ratio

# derived relative competitiveness using rank gap

# 1. Assets per capita
df['assets_per_capita'] = (
    df['total_military_aircraft'] +
    df['tanks'] +
    df['total_naval_fleet']
) / df['total_military_manpower']

# 2. Budget to GDP ratio
df['budget_to_gdp_ratio'] = (
    df['defense_budget_usd'] /
    df['purchasing_power_parity_usd']
)

# 3. Power score & rank
df['power_score'] = (
    df['total_military_aircraft'] +
    df['tanks'] +
    df['total_naval_fleet']
)

df['rank'] = df['power_score'].rank(ascending=False)
df['rank_gap'] = df['rank'] - df['rank'].min()

df[['Country_Code','assets_per_capita','budget_to_gdp_ratio','power_score']]

    Country_Code  assets_per_capita  budget_to_gdp_ratio  power_score
0            USA           0.000121             0.032384        18163
1            RUS           0.000154             0.034922        10614
2            CHN           0.000013             0.009018        10240
3            IND           0.000010             0.007652         6439
4            SKO           0.000138             0.017185         3586
..           ...                ...                  ...          ...
140          LIB           0.000003             0.002224            6
141          SRN           0.000141             0.004745           20
142          CAR           0.000004             0.050624            8
143          BLZ           0.000114             0.006212           18
144          BUT           0.000010             0.002310            2

[145 rows x 4 columns]

In [ ]:
print((df['total_military_manpower'] == 0).sum())
print((df['purchasing_power_parity_usd'] == 0).sum())

0
0

In [ ]:
df['assets_per_capita'].describe()
df['budget_to_gdp_ratio'].describe()
df['power_score'].describe()

count    145.000000
mean       0.019467
std        0.029967
min        0.000085
25%        0.005833
50%        0.012138
75%        0.023780
max        0.308121
Name: budget_to_gdp_ratio, dtype: float64

In [ ]:
df.to_csv('military_final.csv', index=False)