# KPI Generation and Composite Military Strength Index

This notebook generates normalized performance indicators (KPIs)
to remove scale bias and enable fair comparison between countries.
These KPIs are later combined into a composite military strength score.

### Import required libraries

In [1]:
import pandas as pd
import numpy as np

### Reading the Cleaned Dataset

In [2]:
df = pd.read_csv("military_cleaned.csv")
df.columns

Index(['country', 'active_personnel', 'aircraft_carriers', 'aircraft_total',
       'attack_helicopters', 'available_manpower', 'defense_budget',
       'destroyers', 'fighters', 'foreign_exchange_gold', 'frigates',
       'mlrs_rocket_artillery', 'natural_gas_consumption',
       'natural_gas_production', 'oil_consumption', 'oil_production',
       'oil_proven_reserves', 'power_index_rank', 'power_index_score',
       'purchasing_power_parity', 'reserve_personnel',
       'self_propelled_artillery', 'submarines', 'tanks', 'total_assets',
       'total_population'],
      dtype='str')

### KPI 1: Power Index Rank Gap

Formula:
Power Index Rank - 1

Why this KPI?

The Power Index Rank indicates a country’s global military position.
By subtracting 1, we measure how far a country is from the top-ranked nation.

A value of 0 means the country is ranked #1.
Higher values indicate increasing distance from the global leader.

This converts ordinal ranking into a measurable gap indicator,
which is easier to compare and visualize in dashboards.

In [3]:
# Power Index Rank Gap
df["power_index_rank_gap"] = df["power_index_rank"] - 1
df

,country,active_personnel,aircraft_carriers,aircraft_total,attack_helicopters,available_manpower,defense_budget,destroyers,fighters,foreign_exchange_gold,...,power_index_rank,power_index_score,purchasing_power_parity,reserve_personnel,self_propelled_artillery,submarines,tanks,total_assets,total_population,power_index_rank_gap
0,Afghanistan,65.0,145.0,108.0,145.0,43.0,136.0,145.0,145.0,84.0,...,121.0,2.7342,101.0,145.0,145.0,145.0,145.0,53.0,36.0,120.0
1,Albania,134.0,145.0,97.0,145.0,128.0,107.0,145.0,145.0,91.0,...,77.0,1.7258,121.0,145.0,67.0,145.0,145.0,57.0,127.0,76.0
2,Algeria,42.0,145.0,16.0,10.0,29.0,23.0,145.0,20.0,34.0,...,27.0,0.4849,40.0,38.0,21.0,12.0,13.0,33.0,33.0,26.0
3,Angola,53.0,145.0,35.0,31.0,67.0,20.0,145.0,29.0,72.0,...,59.0,1.1045,63.0,145.0,57.0,145.0,45.0,58.0,40.0,58.0
4,Argentina,52.0,145.0,41.0,145.0,32.0,97.0,9.0,48.0,59.0,...,32.0,0.5983,29.0,79.0,60.0,15.0,36.0,52.0,34.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Venezuela,51.0,145.0,43.0,35.0,44.0,51.0,145.0,42.0,79.0,...,51.0,0.9106,90.0,82.0,41.0,14.0,50.0,53.0,49.0,50.0
141,Vietnam,11.0,145.0,38.0,145.0,12.0,35.0,145.0,31.0,33.0,...,23.0,0.4066,25.0,1.0,55.0,12.0,10.0,32.0,16.0,22.0
142,Yemen,90.0,145.0,52.0,31.0,51.0,124.0,145.0,28.0,132.0,...,98.0,2.1617,136.0,145.0,66.0,145.0,145.0,61.0,48.0,97.0
143,Zambia,122.0,145.0,73.0,145.0,68.0,126.0,145.0,145.0,116.0,...,111.0,2.4461,103.0,145.0,66.0,145.0,77.0,53.0,62.0,110.0
144,Zimbabwe,96.0,145.0,72.0,39.0,72.0,77.0,145.0,59.0,139.0,...,105.0,2.2801,114.0,145.0,145.0,145.0,81.0,53.0,71.0,104.0

### KPI 2: Assets per Capita

Formula:
Total Military Assets / Total Population

Why this KPI?

Absolute asset count favors large countries.
This KPI measures military asset availability relative to population size,
showing military intensity instead of raw volume.

It helps identify smaller nations with disproportionately strong military capacity.

In [4]:
df["assets_per_capita"] = df["total_assets"] / df["total_population"]
df

,country,active_personnel,aircraft_carriers,aircraft_total,attack_helicopters,available_manpower,defense_budget,destroyers,fighters,foreign_exchange_gold,...,power_index_score,purchasing_power_parity,reserve_personnel,self_propelled_artillery,submarines,tanks,total_assets,total_population,power_index_rank_gap,assets_per_capita
0,Afghanistan,65.0,145.0,108.0,145.0,43.0,136.0,145.0,145.0,84.0,...,2.7342,101.0,145.0,145.0,145.0,145.0,53.0,36.0,120.0,1.472222
1,Albania,134.0,145.0,97.0,145.0,128.0,107.0,145.0,145.0,91.0,...,1.7258,121.0,145.0,67.0,145.0,145.0,57.0,127.0,76.0,0.448819
2,Algeria,42.0,145.0,16.0,10.0,29.0,23.0,145.0,20.0,34.0,...,0.4849,40.0,38.0,21.0,12.0,13.0,33.0,33.0,26.0,1.000000
3,Angola,53.0,145.0,35.0,31.0,67.0,20.0,145.0,29.0,72.0,...,1.1045,63.0,145.0,57.0,145.0,45.0,58.0,40.0,58.0,1.450000
4,Argentina,52.0,145.0,41.0,145.0,32.0,97.0,9.0,48.0,59.0,...,0.5983,29.0,79.0,60.0,15.0,36.0,52.0,34.0,31.0,1.529412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Venezuela,51.0,145.0,43.0,35.0,44.0,51.0,145.0,42.0,79.0,...,0.9106,90.0,82.0,41.0,14.0,50.0,53.0,49.0,50.0,1.081633
141,Vietnam,11.0,145.0,38.0,145.0,12.0,35.0,145.0,31.0,33.0,...,0.4066,25.0,1.0,55.0,12.0,10.0,32.0,16.0,22.0,2.000000
142,Yemen,90.0,145.0,52.0,31.0,51.0,124.0,145.0,28.0,132.0,...,2.1617,136.0,145.0,66.0,145.0,145.0,61.0,48.0,97.0,1.270833
143,Zambia,122.0,145.0,73.0,145.0,68.0,126.0,145.0,145.0,116.0,...,2.4461,103.0,145.0,66.0,145.0,77.0,53.0,62.0,110.0,0.854839
144,Zimbabwe,96.0,145.0,72.0,39.0,72.0,77.0,145.0,59.0,139.0,...,2.2801,114.0,145.0,145.0,145.0,81.0,53.0,71.0,104.0,0.746479

### KPI 3: Defense Budget to Purchasing Power Ratio

Formula:
Defense Budget / Purchasing Power Parity (PPP)

Why this KPI?

Raw defense budget alone is misleading because
countries have different economic strengths.

This KPI shows how much economic power is allocated
toward military expenditure, reflecting defense priority intensity.

In [5]:
df["budget_to_gdp_ratio"] = (
    df["defense_budget"] / df["purchasing_power_parity"]
)
df

,country,active_personnel,aircraft_carriers,aircraft_total,attack_helicopters,available_manpower,defense_budget,destroyers,fighters,foreign_exchange_gold,...,purchasing_power_parity,reserve_personnel,self_propelled_artillery,submarines,tanks,total_assets,total_population,power_index_rank_gap,assets_per_capita,budget_to_gdp_ratio
0,Afghanistan,65.0,145.0,108.0,145.0,43.0,136.0,145.0,145.0,84.0,...,101.0,145.0,145.0,145.0,145.0,53.0,36.0,120.0,1.472222,1.346535
1,Albania,134.0,145.0,97.0,145.0,128.0,107.0,145.0,145.0,91.0,...,121.0,145.0,67.0,145.0,145.0,57.0,127.0,76.0,0.448819,0.884298
2,Algeria,42.0,145.0,16.0,10.0,29.0,23.0,145.0,20.0,34.0,...,40.0,38.0,21.0,12.0,13.0,33.0,33.0,26.0,1.000000,0.575000
3,Angola,53.0,145.0,35.0,31.0,67.0,20.0,145.0,29.0,72.0,...,63.0,145.0,57.0,145.0,45.0,58.0,40.0,58.0,1.450000,0.317460
4,Argentina,52.0,145.0,41.0,145.0,32.0,97.0,9.0,48.0,59.0,...,29.0,79.0,60.0,15.0,36.0,52.0,34.0,31.0,1.529412,3.344828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Venezuela,51.0,145.0,43.0,35.0,44.0,51.0,145.0,42.0,79.0,...,90.0,82.0,41.0,14.0,50.0,53.0,49.0,50.0,1.081633,0.566667
141,Vietnam,11.0,145.0,38.0,145.0,12.0,35.0,145.0,31.0,33.0,...,25.0,1.0,55.0,12.0,10.0,32.0,16.0,22.0,2.000000,1.400000
142,Yemen,90.0,145.0,52.0,31.0,51.0,124.0,145.0,28.0,132.0,...,136.0,145.0,66.0,145.0,145.0,61.0,48.0,97.0,1.270833,0.911765
143,Zambia,122.0,145.0,73.0,145.0,68.0,126.0,145.0,145.0,116.0,...,103.0,145.0,66.0,145.0,77.0,53.0,62.0,110.0,0.854839,1.223301
144,Zimbabwe,96.0,145.0,72.0,39.0,72.0,77.0,145.0,59.0,139.0,...,114.0,145.0,145.0,145.0,81.0,53.0,71.0,104.0,0.746479,0.675439

### KPI 4: Active Personnel Ratio

Formula:
Active Personnel / Total Population

Why this KPI?

Large countries naturally have more soldiers.
This KPI measures military mobilization level relative to population,
indicating how militarized a nation is proportionally.

In [6]:
df["active_personnel_ratio"] = (
    df["active_personnel"] / df["total_population"]
)
df

,country,active_personnel,aircraft_carriers,aircraft_total,attack_helicopters,available_manpower,defense_budget,destroyers,fighters,foreign_exchange_gold,...,reserve_personnel,self_propelled_artillery,submarines,tanks,total_assets,total_population,power_index_rank_gap,assets_per_capita,budget_to_gdp_ratio,active_personnel_ratio
0,Afghanistan,65.0,145.0,108.0,145.0,43.0,136.0,145.0,145.0,84.0,...,145.0,145.0,145.0,145.0,53.0,36.0,120.0,1.472222,1.346535,1.805556
1,Albania,134.0,145.0,97.0,145.0,128.0,107.0,145.0,145.0,91.0,...,145.0,67.0,145.0,145.0,57.0,127.0,76.0,0.448819,0.884298,1.055118
2,Algeria,42.0,145.0,16.0,10.0,29.0,23.0,145.0,20.0,34.0,...,38.0,21.0,12.0,13.0,33.0,33.0,26.0,1.000000,0.575000,1.272727
3,Angola,53.0,145.0,35.0,31.0,67.0,20.0,145.0,29.0,72.0,...,145.0,57.0,145.0,45.0,58.0,40.0,58.0,1.450000,0.317460,1.325000
4,Argentina,52.0,145.0,41.0,145.0,32.0,97.0,9.0,48.0,59.0,...,79.0,60.0,15.0,36.0,52.0,34.0,31.0,1.529412,3.344828,1.529412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Venezuela,51.0,145.0,43.0,35.0,44.0,51.0,145.0,42.0,79.0,...,82.0,41.0,14.0,50.0,53.0,49.0,50.0,1.081633,0.566667,1.040816
141,Vietnam,11.0,145.0,38.0,145.0,12.0,35.0,145.0,31.0,33.0,...,1.0,55.0,12.0,10.0,32.0,16.0,22.0,2.000000,1.400000,0.687500
142,Yemen,90.0,145.0,52.0,31.0,51.0,124.0,145.0,28.0,132.0,...,145.0,66.0,145.0,145.0,61.0,48.0,97.0,1.270833,0.911765,1.875000
143,Zambia,122.0,145.0,73.0,145.0,68.0,126.0,145.0,145.0,116.0,...,145.0,66.0,145.0,77.0,53.0,62.0,110.0,0.854839,1.223301,1.967742
144,Zimbabwe,96.0,145.0,72.0,39.0,72.0,77.0,145.0,59.0,139.0,...,145.0,145.0,145.0,81.0,53.0,71.0,104.0,0.746479,0.675439,1.352113

### KPI 5: Available Manpower Ratio

Formula:
Available Manpower / Total Population

Why this KPI?

This measures the reserve capacity of a country.
It reflects long-term war sustainability and mobilization potential.

In [7]:
df["manpower_ratio"] = (
    df["available_manpower"] / df["total_population"]
)
df

,country,active_personnel,aircraft_carriers,aircraft_total,attack_helicopters,available_manpower,defense_budget,destroyers,fighters,foreign_exchange_gold,...,self_propelled_artillery,submarines,tanks,total_assets,total_population,power_index_rank_gap,assets_per_capita,budget_to_gdp_ratio,active_personnel_ratio,manpower_ratio
0,Afghanistan,65.0,145.0,108.0,145.0,43.0,136.0,145.0,145.0,84.0,...,145.0,145.0,145.0,53.0,36.0,120.0,1.472222,1.346535,1.805556,1.194444
1,Albania,134.0,145.0,97.0,145.0,128.0,107.0,145.0,145.0,91.0,...,67.0,145.0,145.0,57.0,127.0,76.0,0.448819,0.884298,1.055118,1.007874
2,Algeria,42.0,145.0,16.0,10.0,29.0,23.0,145.0,20.0,34.0,...,21.0,12.0,13.0,33.0,33.0,26.0,1.000000,0.575000,1.272727,0.878788
3,Angola,53.0,145.0,35.0,31.0,67.0,20.0,145.0,29.0,72.0,...,57.0,145.0,45.0,58.0,40.0,58.0,1.450000,0.317460,1.325000,1.675000
4,Argentina,52.0,145.0,41.0,145.0,32.0,97.0,9.0,48.0,59.0,...,60.0,15.0,36.0,52.0,34.0,31.0,1.529412,3.344828,1.529412,0.941176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Venezuela,51.0,145.0,43.0,35.0,44.0,51.0,145.0,42.0,79.0,...,41.0,14.0,50.0,53.0,49.0,50.0,1.081633,0.566667,1.040816,0.897959
141,Vietnam,11.0,145.0,38.0,145.0,12.0,35.0,145.0,31.0,33.0,...,55.0,12.0,10.0,32.0,16.0,22.0,2.000000,1.400000,0.687500,0.750000
142,Yemen,90.0,145.0,52.0,31.0,51.0,124.0,145.0,28.0,132.0,...,66.0,145.0,145.0,61.0,48.0,97.0,1.270833,0.911765,1.875000,1.062500
143,Zambia,122.0,145.0,73.0,145.0,68.0,126.0,145.0,145.0,116.0,...,66.0,145.0,77.0,53.0,62.0,110.0,0.854839,1.223301,1.967742,1.096774
144,Zimbabwe,96.0,145.0,72.0,39.0,72.0,77.0,145.0,59.0,139.0,...,145.0,145.0,81.0,53.0,71.0,104.0,0.746479,0.675439,1.352113,1.014085

In [8]:
#Additional

df["defense_to_gdp_ratio"] = df["defense_budget"] / df["purchasing_power_parity"]

df["oil_self_sufficiency"] = df["oil_production"] / df["oil_consumption"]

In [9]:
# Rounding KPI Columns
kpi=["power_index_rank_gap",
    "assets_per_capita",
    "budget_to_gdp_ratio","active_personnel_ratio",
    "manpower_ratio","defense_to_gdp_ratio",
    "oil_self_sufficiency"
]
   
df[kpi]=df[kpi].round(4)

In [10]:
print(df[[
    "power_index_rank_gap",
    "assets_per_capita",
    "budget_to_gdp_ratio"
]].head())

   power_index_rank_gap  assets_per_capita  budget_to_gdp_ratio
0                 120.0             1.4722               1.3465
1                  76.0             0.4488               0.8843
2                  26.0             1.0000               0.5750
3                  58.0             1.4500               0.3175
4                  31.0             1.5294               3.3448

### Metadata Enrichment

In this step, additional contextual information is added to the dataset 
without altering the core numerical military metrics.

Metadata enrichment includes attributes such as:
- Geographic classification (e.g., continent or region)
- Strategic alliances (e.g., NATO membership)

Why this step is important?

Raw military numbers lack context. 
Two countries may have similar military assets but operate in completely different geopolitical environments.

Metadata allows:
- Group-wise comparisons (region-wise, alliance-wise analysis)
- Segmented visualization
- Context-aware KPI evaluation
- Better strategic interpretation

Important:

Metadata does not change numerical values.
It enhances interpretability and analytical depth.

#### Mapping of Countries with its respective Continent

In [11]:
continent_map = {

    # Asia
    "Afghanistan": "Asia",
    "Armenia": "Asia",
    "Azerbaijan": "Asia",
    "Bahrain": "Asia",
    "Bangladesh": "Asia",
    "Bhutan": "Asia",
    "Cambodia": "Asia",
    "China": "Asia",
    "Georgia": "Asia",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Israel": "Asia",
    "Japan": "Asia",
    "Jordan": "Asia",
    "Kazakhstan": "Asia",
    "Kuwait": "Asia",
    "Kyrgyzstan": "Asia",
    "Laos": "Asia",
    "Lebanon": "Asia",
    "Malaysia": "Asia",
    "Mongolia": "Asia",
    "Myanmar": "Asia",
    "Nepal": "Asia",
    "North Korea": "Asia",
    "Oman": "Asia",
    "Pakistan": "Asia",
    "Philippines": "Asia",
    "Qatar": "Asia",
    "Saudi Arabia": "Asia",
    "Singapore": "Asia",
    "South Korea": "Asia",
    "Sri Lanka": "Asia",
    "Syria": "Asia",
    "Taiwan": "Asia",
    "Tajikistan": "Asia",
    "Thailand": "Asia",
    "Turkiye": "Asia",
    "Turkmenistan": "Asia",
    "United Arab Emirates": "Asia",
    "Uzbekistan": "Asia",
    "Vietnam": "Asia",
    "Yemen": "Asia",

    # Europe
    "Albania": "Europe",
    "Austria": "Europe",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Bosnia and Herzegovina": "Europe",
    "Bulgaria": "Europe",
    "Croatia": "Europe",
    "Czechia": "Europe",
    "Denmark": "Europe",
    "Estonia": "Europe",
    "Finland": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Greece": "Europe",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "Ireland": "Europe",
    "Italy": "Europe",
    "Kosovo": "Europe",
    "Latvia": "Europe",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Moldova": "Europe",
    "Montenegro": "Europe",
    "Netherlands": "Europe",
    "North Macedonia": "Europe",
    "Norway": "Europe",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Romania": "Europe",
    "Russia": "Europe",
    "Serbia": "Europe",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Spain": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Ukraine": "Europe",
    "United Kingdom": "Europe",

    # Africa
    "Algeria": "Africa",
    "Angola": "Africa",
    "Benin": "Africa",
    "Botswana": "Africa",
    "Burkina Faso": "Africa",
    "Cameroon": "Africa",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Democratic Republic of the Congo": "Africa",
    "Egypt": "Africa",
    "Eritrea": "Africa",
    "Ethiopia": "Africa",
    "Gabon": "Africa",
    "Ghana": "Africa",
    "Ivory Coast": "Africa",
    "Kenya": "Africa",
    "Liberia": "Africa",
    "Libya": "Africa",
    "Madagascar": "Africa",
    "Mali": "Africa",
    "Mauritania": "Africa",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Namibia": "Africa",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "Republic of the Congo": "Africa",
    "Senegal": "Africa",
    "Sierra Leone": "Africa",
    "Somalia": "Africa",
    "South Africa": "Africa",
    "South Sudan": "Africa",
    "Sudan": "Africa",
    "Tanzania": "Africa",
    "Tunisia": "Africa",
    "Uganda": "Africa",
    "Zambia": "Africa",
    "Zimbabwe": "Africa",

    # North America
    "Beliz": "North America",
    "Canada": "North America",
    "Cuba": "North America",
    "Dominican Republic": "North America",
    "El Salvador": "North America",
    "Guatemala": "North America",
    "Honduras": "North America",
    "Mexico": "North America",
    "Nicaragua": "North America",
    "Panama":"North Ameria",
    "United States": "North America",

    # South America
    "Argentina": "South America",
    "Bolivia": "South America",
    "Brazil": "South America",
    "Chile": "South America",
    "Colombia": "South America",
    "Ecuador": "South America",
    "Paraguay": "South America",
    "Peru": "South America",
    "Suriname": "South America",
    "Uruguay": "South America",
    "Venezuela": "South America",

    # Oceania
    "Australia": "Oceania",
    "New Zealand": "Oceania"
}

In [12]:
#Mapping the Countries to it's Continents
df["continent"] = df["country"].map(continent_map)

In [13]:
#Check the Null Values
df["continent"].isna().sum()

np.int64(0)

In [14]:
missing_countries = df[df["continent"].isna()]["country"].unique()
print(missing_countries)

<StringArray>
[]
Length: 0, dtype: str

#### NATO Memberships

In [15]:
#NATO
nato_members = [
    "Albania",
    "Belgium",
    "Bulgaria",
    "Canada",
    "Croatia",
    "Czechia",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Montenegro",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Turkiye",
    "United Kingdom",
    "United States"
]


df["is_nato_member"] = df["country"].isin(nato_members).astype(int)

In [16]:
# To display the Ccolumns available
df.columns

Index(['country', 'active_personnel', 'aircraft_carriers', 'aircraft_total',
       'attack_helicopters', 'available_manpower', 'defense_budget',
       'destroyers', 'fighters', 'foreign_exchange_gold', 'frigates',
       'mlrs_rocket_artillery', 'natural_gas_consumption',
       'natural_gas_production', 'oil_consumption', 'oil_production',
       'oil_proven_reserves', 'power_index_rank', 'power_index_score',
       'purchasing_power_parity', 'reserve_personnel',
       'self_propelled_artillery', 'submarines', 'tanks', 'total_assets',
       'total_population', 'power_index_rank_gap', 'assets_per_capita',
       'budget_to_gdp_ratio', 'active_personnel_ratio', 'manpower_ratio',
       'defense_to_gdp_ratio', 'oil_self_sufficiency', 'continent',
       'is_nato_member'],
      dtype='str')

In [17]:
#To shows the mismatches
set(nato_members) - set(df["country"])

set()

In [18]:
df.to_excel("military_final.xlsx", index=False)